"""Add language to posts

Revision ID: 2500e0306fdb
Revises: 265bbe0c7758
Create Date: 2025-03-31 10:53:52.943081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2500e0306fdb'
down_revision = '265bbe0c7758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
